services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - typesense
    ports:
      - "8000:8000"
    env_file:
      - .env

  typesense:
    image: typesense/typesense:0.23.1
    command: >
      typesense-server
        --data-dir /data
        --api-key ${TYPESENSE_API_KEY}
        --listen-port 8108
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data

volumes:
  typesense-data:
